### ISSUE TITLE
Update UG/DG for Battleship feature

### ISSUE THREAD

**Issue by iwle** [CS2103-AY1819S2-W14-3/main#206]
Update user guide and developer guide for Battleship feature:

**User Guide**

- [x] Describe commands `putShip`, `listTags` and `list` in greater detail in UG. See #209.
- [x] Add more examples for above commands in UG. See #209.

**Developer Guide**

- [x] Describe implementation of the above commands in DG. See #230.
- [x] Discuss aspects of implementing the above commands in DG. See #230.
- [x] Update User Stories for above commands in DG. See #212.
- [x] Update Use Cases for above commands in DG. See #212.
- [x] Write out instructions for manual scripted test for above commands in DG. See #212.
- [x] Port relevant changes over to PPP in Week 13. (Brought over to `v1.4` milestone).

**Comment by iwle** [comment]
Have to explain the head coordinate. See #217. Will do so in the next UG PR.

**Comment by iwle** [comment]
Completed. See #209, #212, #217, and #230.
