### ISSUE TITLE
Update UG/DG for Battle feature

### ISSUE THREAD

**Issue by s-tr** [CS2103-AY1819S2-W14-3/main#210]
Update user guide and developer guide for Battleship feature:

**User Guide**

- [x] Describe commands `begin` and `attack` in greater detail in UG. (done)

**Developer Guide**

- [x] Describe implementation of the above commands in DG. (done)
- [x] Discuss aspects of implementing the above commands in DG. (done)
- [x] Add class diagram for the Battle component. (#387)
- [x] Add sequence diagrams for the above command. (#387)
- [x] Update User Stories for above commands in DG. (#400)
- [x] Update Use Cases for above commands in DG. (#387)
- [x] Write out instructions for manual scripted test for above commands in DG. (#400)
- [x] Port relevant changes over to PPP in Week 13. (#408)
