### ISSUE TITLE
Remove AB4 elements

### ISSUE THREAD

**Issue by s-tr** [CS2103-AY1819S2-W14-3/main#275]
- [x] Remove unused Commands, e.g. `SelectCommand` - fixed in #274.
- [x] Remove references to person list - fixed in #338.
- [x] Remove unused data classes, e.g. `Email` - fixed in #338.
- [x] Remove unused methods, e.g., `getCell()` in `MapGrid`. See #280.
- [x] Remove unused methods and tests for `Logic` - fixed in #279.
- [x] Remove unused methods and tests for `Model` - fixed in #336.
- [x] Remove storage stuff.
