### ISSUE TITLE
Some diagrams are inappropriate or contain errors

### ISSUE THREAD

**Issue by s-tr** [CS2103-AY1819S2-W14-3/main#394]
General
 - [x] In the "How the architecture components interact with each other" section, the command needs to be updated (fixed in #396)

Logic component

 - [x] The class diagram needs to be updated (#376, #378). Addressed in #396.

Map feature

 - [x] In "Current implementation" section, the code snippets do not link to actual code

Ship Management feature

 - [x] In "Putting ships" section, the sequence diagram references `AddressBookParser` (#376). Resolved in #396.
 - [x] In "Listing tags" section, the sequence diagram is broken. Resolved in #396.
 - [x] In "Listing tags" section, the code does not render on my PC, I am not sure if it also does not render on others'. Addressed in #396.

Enemy feature

 - [x] In "placeMultipleDestroyerAndCruiser" section, the [loop] has to end before the method return

Statistics feature

 - [x] In "Display statistics" section, the sequence diagram references `AddressBookParser` (#376)
 - [x] In "Save and compare" section, the image `StatsWinScreen.png` is not found
 - [x] In "Activity diagram" section, the diagram is not yet drawn

**Comment by erjillsison** [comment]
I think the code snippets only render when viewed through the project website: https://cs2103-ay1819s2-w14-3.github.io/main/DeveloperGuide.html

**Comment by iwle** [comment]
`ListTagsCommand` sequence diagram will be removed.

**Comment by iwle** [comment]
`Logic` component class diagram updated in #396. @erjillsison possible to take a look at it? Thanks.

**Comment by erjillsison** [comment]
> 
> 
> `Logic` component class diagram updated in #396. @erjillsison possible to take a look at it? Thanks.

the "XYZ Commands = AddCommand, etc" still needs updating

**Comment by iwle** [comment]
Ok. Updated.

**Comment by s-tr** [comment]
Thanks a lot ^-^
